# Header
menu:
  首页: /
  关于: /about
#  友链: /links
#  TAGS: /tags
#  CATEGORIES: /categories
# logo: https://qiniu.miiiku.xyz/src/images/logo.png
banner: http://qapo6pgc5.bkt.clouddn.com/image/banner-7.jpg
# banner: css/images/banner.jpg

# large cover
# long: [article, link]
# short: [category, tag]
large_legnth:
  long: 20
  short: 5

# 一言
# docs: https://hitokoto.cn/api
# type: [a, b, c, d, e, f, g]
hitokoto:
  enable: true
  type: a

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn
valine:
  enable: true
  appId:
  appKey:
  avatar: mm
  placeholder: 随便说点什么叭～
  notify: false
  visitor: false
  recordIP: true
  pageSize: 10

disqus:
  enable: false
  website:
  error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# waterfall 瀑布流
# docs: https://github.com/miiiku/waterfall
# Specific configuration information go to `layout/plug-in/waterfall.ejs`
waterfall:
  enable: true

# zoom 图片预览
# docs: https://github.com/miiiku/zoom
# Specific configuration information go to `layout/plug-in/zoom.ejs`
zoom:
  enable: true


# widget behavior
archive_type: 'monthly'
show_count: false

# beian
beian:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
favicon: /favicon.ico

# 替换文章的链接内容为格式化以后的时间
permalink: true

page_anchor:
  enable: true

# Social Icon
social_icon:
  header_enable: true
  footer_enable: true
  icons:
    - { type: email,      value: }
    - { type: github,     value: https://github.com/Lengbumo/}
    - { type: google+,    value: }
    - { type: ins,        value: }
    - { type: twitter,    value: }
    - { type: youtube,    value: }
    - { type: weibo,      value: }
    - { type: cloudmusic, value: }
    - { type: zhihu,      value: }
